<article class="features row"><div class="col">
    <h1>Contact Us</h1>

    <ul>
        <li>
            Support can be found on the <a href="https://discourse.laminas.dev/c/questions/api-tools/8">forums</a>
            and the <a href="https://laminas.dev/chat/">Laminas Slack</a> channel <strong>"#api-tools"</strong>.
        </li>

        <li>
            Development discussions occur on the <a href="https://discourse.zendframework.com/c/contributors/10">forums</a>
            and the <a href="https://laminas.dev/chat/">Laminas Slack</a> channel <strong>"#api-tools-contrib"</strong>.
        </li>

        <li>
            Issues may be reported at the appropriate repositories 
            under the github organization <a href="https://github.com/laminas-api-tools">laminas-api-tools</a>.
        </li>

        <li>
            Patches may be submitted via github to the appropriate 
            repositories under <a href="https://github.com/laminas-api-tools">laminas-api-tools</a>.
        </li>
    </ul>

    <div class="card mt-5"><div class="card-body">
        <h3 class="card-title">Reporting issues</h3>
        
        <p class="card-text">
            Laminas API Tools consists of <a href="https://docs.laminas.dev/mvc/">Laminas MVC</a> modules,
            and thus has many different repositories. If you are unsure which
            repository to report against, we recommend the following:
        </p>

        <ul class="list-group list-group-flush">
            <li class="list-group-item">For issues encountered in the administrative user interface,
                report against <a href="https://github.com/laminas-api-tools/api-tools-admin/issues">laminas-api-tools/api-tools-admin</a></li>

            <li class="list-group-item">For all other issues, report against
                <a href="https://github.com/laminas-api-tools/api-tools/issues">laminas-api-tools/api-tools</a></li>
        </ul>
    </div></div>

    <h2>Follow us on Twitter</h2>

    <p>
        You can reach us on Twitter by following the 
        <a href="https://twitter.com/getlaminas">@getlaminas</a> account.
    </p>
</div></article>
