<section class="features row">
    <h1>Apigility Introduction</h1>

    <div class="embed-responsive embed-responsive-16by9">
        <iframe
            class="embed-responsive-item"
            src="https://www.youtube.com/embed/ZBSX1AB6LcM"
            allowfullscreen></iframe>
    </div>

    <blockquote class="blockquote">
        The above video references Apigility, the predecessor to Laminas API
        Tools. While some details differ, particularly around class names, the
        overall workflow remains the same.
    </blockquote>
</section>
