<?php
$toc     = $this->markdownpage('TOC', $this->model, false);
$baseUri = $this->url('documentation', [], false);
$current = sprintf('%s/%s', $baseUri, $this->current);
?>
<aside class="manual-toc d-none d-xl-block col-md-2 col-xl-3 order-2 mt-5" aria-label="Documentation table of contents">
    <?= $toc ?>
</aside>

<?php $this->inlineScript()->captureStart(); ?>
$('a[href="<?= $current; ?>"]').parent('li').addClass('current').parents('ul').show();
<?php $this->inlineScript()->captureEnd(); ?>
