<section class="intro row">
    <div class="jumbotron bg-api-tools">
        <h1 class="text-white">The world's easiest way to create high-quality APIs</h1>
    </div>
</section>

<section class="features row card-deck">
    <div class="card"><div class="card-body">
        <h2 class="card-title">Be API-centric</h2>

        <p class="card-text">
            Separating presentation logic from data provides the flexibility
            to support multiple client form factors, and future-proofs apps to
            allow behind-the-scenes change without breaking user interfaces.
            With Laminas API Tools, you can take the code that powers your
            business, and then API-enable it.
        </p>
    </div></div>

    <div class="card"><div class="card-body">
        <h2 class="card-title">Think mobile</h2>

        <p class="card-text">
            An API-based architecture is essential to agile delivery of mobile
            applications. Laminas API Tools provides JSON representations that can be
            parsed and used in any mobile framework; write for the web or native
            applications simultaneously!
        </p>
    </div></div>

    <div class="card"><div class="card-body">
        <h2 class="card-title">Continuing Apigility's Legacy</h2>

        <p class="card-text">
            Laminas API Tools is the open source continuation of Apigility.
        </p>
    </div></div>
</section>

<section class="quickstart row mt-5 jumbotron bg-dark">
    <div class="col">
        <h4 class="text-white">
            Startup <em>in&nbsp;seconds</em>
        </h4>
    </div>

    <div class="col-8 card bg-dark"><div class="card-body">
        <pre><code class="language-bash">
$ composer create-project laminas-api-tools/api-tools-skeleton
$ cd api-tools-skeleton
$ php -S 0.0.0.0:8080 -t public public/index.php
        </code></pre>
    </div></div>
</section>

<section class="platforms row card-deck">
    <div class="card">
        <div class="card-body">
            <div class="embed-responsive embed-responsive-16by9">
                <iframe
                    class="embed-responsive-item"
                    allowfullscreen
                    src="https://www.youtube.com/embed/ZBSX1AB6LcM"></iframe>
            </div>
            <p class="card-text">
                Want an overview of Laminas API Tools features?
                <br />
                Watch the video above, or <a href="<?= $this->url('video') ?>">others here</a>
            </p>

            <p class="card-text"><em>
                The above video references Apigility, the predecessor to Laminas
                API Tools. While some details differ, particularly around class names, the
                overall workflow remains the same.
            </em></p>
        </div>
    </div>

    <div class="card"><div class="card-body">
        <h2 class="card-title">Key features</h2>

        <p class="card-text">
            RESTful or RPC services; JSON (specifically,
            <a href="http://tools.ietf.org/html/draft-kelly-json-hal-08">HAL</a>);
            <a href="https://tools.ietf.org/html/rfc7807">Problem Details for HTTP APIs</a>;
            Versioning; Normalisation and Validation; Authentication (HTTP Basic/Digest, OAuth2);
            Documentation (HTML, Swagger, API Blueprint).
        </p>

        <p class="card-text"><a href="<?= $this->url('documentation') ?>">Discover more</a> &gt;</p>

        <h2 class="card-title">Runs everywhere</h2>

        <p class="card-text"><img
            src="img/platforms.png"
            alt="PHP, Mac, Windows, GNU/Linux"
            title="PHP, Mac, Windows, GNU/Linux"
            class="responsive"></p>
    </div></div>
</section>
