<?php

use League\CommonMark\Environment\Environment;
use League\CommonMark\Extension\CommonMark\CommonMarkCoreExtension;
use League\CommonMark\Extension\GithubFlavoredMarkdownExtension;
use League\CommonMark\Extension\Table\TableExtension;
use League\CommonMark\MarkdownConverter;

$environment = new Environment([]);
$environment->addExtension(new CommonMarkCoreExtension());
$environment->addExtension(new GithubFlavoredMarkdownExtension());
$environment->addExtension(new TableExtension());
$parser = new MarkdownConverter($environment);
?>
<section class="docs row flex-xl-nowrap">
    <?= $this->partial('layout/aside', [
        'aside'   => $this->aside,
        'current' => $this->current,
    ]) ?>

    <article class="col-md-10 col-xl-9 py-md-3 pl-md-5">
        <h1><?= $this->version ?> Changelog</h1>

        <?= $parser->convert($this->changelog) ?>
    </article>
</section>
