<?php $parser = new \League\CommonMark\CommonMarkConverter() ?>
<section class="docs row flex-xl-nowrap">
    <?= $this->partial('layout/aside', [
        'aside'   => $this->aside,
        'current' => $this->current,
    ]) ?>

    <article class="col-md-9 col-xl-8 py-md-3 pl-md-5">
        <h1><?= $this->version ?> Changelog</h1>

        <?= $parser->convertToHtml($this->changelog) ?>
    </article>
</section>
