<?= $this->doctype(); ?>
<html>
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Laminas API Tools')->setSeparator(' - ')->setAutoEscape(false) ?>
    <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendName('description', 'Laminas API Tools: Quickly build and deploy high quality APIs')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge') ?>

    <?= $this
            ->headLink([
                'rel' => 'shortcut icon',
                'type' => 'image/vnd.microsoft.icon',
                'href' => $this->basePath() . '/img/trademark-laminas-api-tools.svg'
            ])
            ->appendStylesheet($this->basePath('/') . 'css/styles.min.css')
    ?>

    <?php

        $this->inlineScript()
            ->prependFile($this->basePath('/') . 'js/scripts.min.js')
    ?>
</head>
<body id="page-top" class="api-tools">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            <a class="logo-link navbar-brand" href="https://getlaminas.org/" data-tooltip data-placement="bottom" title="Go to the Laminas homepage">
                <img src="/img/laminas-foundation-white.svg" height="28" alt="Laminas">
            </a>
            <a class="navbar-title" href="/" data-tooltip data-placement="bottom" title="Go to the Laminas API Tools home page">API Tools</a>

            <button type="button"
                    class="navbar-toggler"
                    data-toggle="collapse"
                    data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <div class="dropdown">
                            <a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false">
                                All Docs
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" href="https://docs.laminas.dev/components">Components</a>
                                <a class="dropdown-item" href="https://docs.mezzio.dev/">Mezzio</a>
                                <a class="dropdown-item" href="https://api-tools.getlaminas.org/documentation">API Tools</a>
                                <a class="dropdown-item" href="https://docs.laminas.dev/mvc">MVC</a>
                            </div>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a href="https://getlaminas.org/participate" class="nav-link">Community</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <header class="header navbar navbar-expand-lg">
        <div class="container">
            <h1 class="header__title">API Tools</h1>

            <button type="button"
                    class="navbar-toggler subnav-control"
                    data-toggle="collapse"
                    data-target="#subnavContent"
                    aria-controls="subnavContent"
                    aria-expanded="false"
                    aria-label="Toggle subnavigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="subnavContent">
                <?= $this->navigation('navigation')->menu()->setPartial('layout/menu'); ?>
            </div>
        </div>
    </header>

    <div class="container content">
        <?= $this->content ?>
    </div>

    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <a class="footer__button" href="#page-top"><i class="fa fa-chevron-up" aria-hidden="true"></i></a>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <h5>Laminas</h5>
                    <ul>
                        <li>Laminas Project <a href="https://getlaminas.org/">Components and MVC for Enterprise Applications</a></li>
                        <li>Mezzio <a href="https://docs.mezzio.dev/">PSR-15 Middleware in Minutes</a></li>
                        <li>Laminas API Tools: <a href="https://api-tools.getlaminas.org/">Build RESTful APIs in minutes</a></li>
                    </ul>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <h4 class="footer__headline">Support</h4>
                    <ul class="support__list">
                        <li class="support__list-item">
                            <a href="https://discourse.laminas.dev" class="support__link" title="Forum"><i class="fa fa-comments"></i></a>
                        </li>
                        <li class="support__list-item">
                            <a href="https://laminas.dev/chat" class="support__link" title="Chat"><i class="fa fa-slack"></i></a>
                        </li>
                        <li class="support__list-item">
                            <a href="https://github.com/laminas-api-tools" class="support__link" title="Github"><i class="fa fa-github"></i></a>
                        </li>
                        <li class="support__list-item">
                            <a href="https://twitter.com/getlaminas" class="support__link" title="Twitter"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li class="support__list-item">
                            <a href="https://getlaminas.org/blog/feed-rss.xml" class="support__link" title="Blog feed"><i class="fa fa-rss"></i></a>
                        </li>
                        <li class="support__list-item">
                            <a href="https://getlaminas.org/security/feed" class="support__link" title="Security feed"><i class="fa fa-rss-square"></i></a>
                        </li>
                    </ul>
                </div>

                <div class="col-md-6">
                    <h4 class="footer__headline">Copyright</h4>
                    <p>
                        &copy; 2020 <a href="https://getlaminas.org/">Laminas Project</a> a Series of LF Projects, LLC.
                    </p>
                </div>
            </div>

            <div class="row align-items-center justify-content-between mt-5 border-top border-white">
                <div class="col text-left">
                    <div class="platform_sh_widget">
                        Hosting sponsored by the <a title="platform.sh" href="https://platform.sh/?medium=referral&utm_campaign=sponsored_sites&utm_source=laminas_getlaminas_org"><img class="platformsh-logo" src="https://platform.sh/logos/redesign/Platformsh_logo_white@2x.png" alt="platform.sh logo" style="padding: 0 3px 0 3px;height: 1.1em; vertical-align: text-bottom;"/></a> <a href="https://platform.sh/?medium=referral&utm_campaign=sponsored_sites&utm_source=laminas_getlaminas_org">PHP Cloud Hosting</a> Service
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <?= $this->inlineScript() ?>
</body>
</html>
